---
- name: "Get checksum list"
  set_fact:
    __prometheus_checksums: "{{ lookup('url', 'https://github.com/prometheus/prometheus/releases/download/v' + prometheus_version + '/sha256sums.txt', wantlist=True) | list }}"
  run_once: true

- name: "Get checksum for amd64 architecture"
  set_fact:
    __prometheus_checksum: "{{ item.split(' ')[0] }}"
  with_items: "{{ __prometheus_checksums }}"
  when:
    - "('linux-amd64.tar.gz') in item"

- name: download prometheus binary to local folder
  become: false
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    checksum: "sha256:{{ __prometheus_checksum }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  # run_once: true # <-- this cannot be set due to multi-arch support
  delegate_to: localhost
  check_mode: false

- name: unpack prometheus binaries
  become: false
  unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
  delegate_to: localhost
  check_mode: false

- name: propagate official prometheus and promtool binaries
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_binary_install_dir }}/{{ item }}"
    mode: "0755"
    owner: root
    group: root
  with_items:
    - prometheus
    - promtool
  notify:
    - restart prometheus

- name: propagate official console templates
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}/"
    dest: "{{ prometheus_config_dir }}/{{ item }}/"
    mode: "0644"
    owner: root
    group: root
  with_items:
    - console_libraries
    - consoles
  notify:
    - restart prometheus
