---
- name: Provision vagrant instance
  hosts: all
  vars:
    #selinux_mode: enforcing
    selinux_mode: permissive
    selinux_reboot: yes
    selinux_utils: yes
    prometheus_scrape_configs:
      - job_name: "node_exporter"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "localhost:9100"
  roles:
    - name: ansible-role-selinux
      become: yes
      when: ansible_facts['os_family'] == 'RedHat'
    - name: ansible-role-prometheus
      become: yes
    - name: ansible-role-node_exporter
      become: yes
