---
- name: Provide node_exporter config
  template:
    src: "{{ node_exporter_config_file }}"
    dest: "{{ node_exporter_config_dir }}/node_exporter.yml"
    force: true
    owner: root
    group: node_exporter
    mode: 0644
  when: node_exporter_config | bool
  notify:
    - reload node_exporter

- name: create systemd service unit
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart node_exporter

- name: Start and enable node_exporter service
  systemd:
    name: node_exporter.service
    enabled: "{{ node_exporter_autostart | bool }}"
    state: "{{ node_exporter_state }}"
