---
- name: Add nginx repo key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present
  become: "{{ nginx_become }}"

- name: Add repo
  apt_repository:
    repo: "deb http://nginx.org/packages/mainline/ubuntu {{ ansible_distribution_release }} nginx"
    state: present
    update_cache: yes
    validate_certs: yes
  become: "{{ nginx_become }}"

- name: Install nginx
  apt:
    name: "nginx={{ nginx_version }}*"
    state: present
  become: "{{ nginx_become }}"
