---
- name: Allow nginx to listen on tcp port "{{ nginx_site_listen }}"
  seport:
    ports: "{{ nginx_site_listen }}"
    proto: tcp
    setype: "{{ nginx_selinux_seport_type }}"
    state: present

- name: Allow nginx to connect to upstreams
  seport:
    ports: "{{ item }}"
    proto: tcp
    setype: "{{ nginx_selinux_connect_seport_type }}"
    state: present
  loop: "{{ nginx_selinux_upstream_ports }}"
