---
# geerlingguy.elasticsearch already has geerlingguy.java as requirement
- src: geerlingguy.java
  version: 1.10.0

- src: geerlingguy.elasticsearch
  version: 5.0.0

- src: geerlingguy.kibana
  version: 4.0.1

- src: geerlingguy.filebeat
  version: 3.0.2

- src: robertdebock.auditd
  version: 2.7.6
